### ISSUE TITLE
Missing dependency on tqdm

### ISSUE THREAD

**Issue by natefoo** [refgenie/refgenconf#134]
In a fresh Python 3.6 venv:

```
(refgenie-0.12) [refgenie@cvmfs0-psu0 ~]$ pip install refgenie
...lots of output
Installing collected packages: numpy, jsonschema, idna, dataclasses, commonmark, colorama, charset-normalizer, certifi, attmap, yacman, rich, requests, pyfaidx, psutil, pandas, logmuse, future, refgenconf, piper, refgenie
Successfully installed attmap-0.13.0 certifi-2021.5.30 charset-normalizer-2.0.6 colorama-0.4.4 commonmark-0.9.1 dataclasses-0.8 future-0.18.2 idna-3.2 jsonschema-3.2.0 logmuse-0.2.7 numpy-1.19.5 pandas-1.1.5 piper-0.12.1 psutil-5.8.0 pyfaidx-0.6.2 refgenconf-0.12.0 refgenie-0.12.0 requests-2.26.0 rich-10.11.0 yacman-0.8.3

(refgenie-0.12) [refgenie@cvmfs0-psu0 ~]$ refgenie upgrade --target-version 0.4
Traceback (most recent call last):
  File "/home/refgenie/refgenie-0.12/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/refgenie/refgenie-0.12/lib64/python3.6/site-packages/refgenie/cli.py", line 417, in main
    target_version=args.target_version, filepath=gencfg, force=args.force
  File "/home/refgenie/refgenie-0.12/lib64/python3.6/site-packages/refgenconf/refgenconf.py", line 2875, in upgrade_config
    from .refgenconf_v03 import _RefGenConfV03 as OldRefGenConf
  File "/home/refgenie/refgenie-0.12/lib64/python3.6/site-packages/refgenconf/refgenconf_v03.py", line 21, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

It works after installing `tqdm` by hand:

```
(refgenie-0.12) [refgenie@cvmfs0-psu0 ~]$ pip install tqdm
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.62.3

(refgenie-0.12) [refgenie@cvmfs0-psu0 ~]$ refgenie upgrade --target-version 0.4
Upgrading config to v0.4. Current genome identifiers will be replaced with sequence-derived digests and contents of '/cvmfs/refgenomes-databio.galaxyproject.org' will be moved to 'data' and 'alias' directories. For more info visit: http://refgenie.databio.org/en/latest/upgrade_config/. Would you like to proceed? [y/N]
```

**Comment by nsheff** [comment]
@stolarczyk and @xuebingjie1990 didn't you move away from tqdm in favor of rich? Is this just an import that should have been removed?
